platforms:
  rpipico:
    board: rp2040:rp2040:rpipico
    package: rp2040:rp2040
    gcc:
      features:
      defines:
        - ARDUINO_ARCH_RP2040
      warnings:
      flags:

packages:
  rp2040:rp2040:
    url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

################################
#
#  attiny85 fails to install in build-CI
#  tried two configurations.
#
# platforms:
  # attiny85:
    # board: attiny:attiny:attiny85
    # package: attiny:attiny
    # gcc:
      # features:
      # defines:
        # - ARDUINO_attiny
      # warnings:
      # flags:

# packages:
  # attiny:attiny:
    # url: https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json


platforms:
  attiny85opti:
    board: ATTinyCore:avr:attinyx5opti
    package: ATTinyCore:avr
    gcc:
      features:
      defines:
        - ARDUINO_AVR_ATTINYX5
      warnings:
      flags:

packages:
  ATTinyCore:avr:
    url: https://drazzy.com/package_drazzy.com_index.json



################################

compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - attiny85opti
    # - uno
    # - due
    # - zero
    # - leonardo
    # - m4
    # - esp32
    # - esp8266
    # - mega2560
    # - rpipico

  libraries:
    #   libraries not registered?
    - "TinyWireM"
    - "TinyLiquidCrystal_I2C"
